### ISSUE TITLE
Admin log in and user creation

### ISSUE THREAD

**Issue by innocentmm** [codersforcauses/FoGUWA#37] opened 2020-01-01 16:30 UTC
This can be done as a function within the “Roles” admin page as “create user” with a set of criteria including the set up of a user name and password. I will speak to FoG about what information they would like to see. Look into [this](https://auth0.com/docs/quickstarts) to add auth integration using passport or use Mongo or another authentication service and or database. When using auth, the frontend UI component is optional because you can use the auth0 default or choose your own based on their theme so the only thing here would be to set it to FoGs colours. Use CFCs auth account but set up a new API for this project. Message a PM for access.

- [ ] Set up auth and routes

- [ ] Match login pop up colours to FoG theme

**Comment by Drewbi** [comment] 2020-01-04 16:15
Duplicate of #15

**Closed as completed by Drewbi** 2020-01-04 16:15 UTC
